### ISSUE TITLE
Unable to get connected to Nefit Cloud

### ISSUE THREAD

**Issue by powergrim** [RaimondB/node-red-contrib-nefit-easy#115]
**Describe the bug**
Im trying to get the node to work, but inside node-red it keeps saying that the node is "disconnected". Im not really experienced with node-red, but Im trying to read the status of my Nefit heater as a means of first steps to learn node-red in combination with Nefit Easy.

**To Reproduce**
Ive downloaded the nodes, added them to my pallete and created a flow with one. One that sends an "on" payload every minute as a means to test. And I`ve created a debug node to see some output. None of which is generated and the node keeps saying "disconnected" within the flow editor. I cant really find errors in the log, the mentioned disconnects only occur when I redeploy my nodes, seems normal to me.

This is a part of a tail from my syslog including the node-red messages:

Jul 18 11:11:30 bvdh-domo02 Node-RED[1195]: Welcome to Node-RED
Jul 18 11:11:30 bvdh-domo02 Node-RED[1195]: ===================
Jul 18 11:11:30 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:30 - [info] Node-RED version: v0.20.7
Jul 18 11:11:30 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:30 - [info] Node.js  version: v10.16.0
Jul 18 11:11:30 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:30 - [info] Linux 4.19.57-v7+ arm LE
Jul 18 11:11:31 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:31 - [info] Loading palette nodes
Jul 18 11:11:37 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:37 - [info] Settings file  : /home/pi/.node-red/settings.js
Jul 18 11:11:37 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:37 - [info] Context store  : 'default' [module=memory]
Jul 18 11:11:37 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:37 - [info] User directory : /home/pi/.node-red
Jul 18 11:11:37 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:37 - [warn] Projects disabled : editorTheme.projects.enabled=false
Jul 18 11:11:37 bvdh-domo02 Node-RED[1195]: 18 Jul 11:11:37 - [info] Flows file     : /home/pi/.node-red/flows_BVDH-DOMO02.json
...
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] Stopping flows
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] [nefit-easy-config:5eadceac.f8047] Nefit Easy Client disconnected from the Bosch backend.
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] Stopped flows
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] Starting flows
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] [nefit-easy-config:5eadceac.f8047] Starting Nefit Easy Node for Node-RED.
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] Started flows
Jul 18 12:53:56 bvdh-domo02 Node-RED[1499]: 18 Jul 12:53:56 - [info] [server:Home Assistant] WebSocket Connected to http://localhost:8123
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] Stopping flows
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] [server:Home Assistant] Closing WebSocket http://localhost:8123
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] [nefit-easy-config:5eadceac.f8047] Nefit Easy Client disconnected from the Bosch backend.
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] Stopped flows
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] Starting flows
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] [nefit-easy-config:5eadceac.f8047] Starting Nefit Easy Node for Node-RED.
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] Started flows
Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] [server:Home Assistant] WebSocket Connected to http://localhost:8123

**Expected behavior**
I expect some output to appear in my debug node.

**Desktop (please complete the following information):**
 - OS: 
 Distro......: Raspbian GNU/Linux 10 (buster)
 Kernel......: Linux 4.19.57-v7+

**Comment by RaimondB** [comment]
Sorry, I totally missed this one due to vacations. 

This line shows the node is doing work:
`Jul 18 12:55:29 bvdh-domo02 Node-RED[1499]: 18 Jul 12:55:29 - [info] [nefit-easy-config:5eadceac.f8047] Starting Nefit Easy Node for Node-RED.`

Is the issue still there? What does your flow look like?

Pro-Tip: You need to trigger the node e.g. with a Timestamp node if you want to do a periodic reading. It will not generate messages without an external trigger.

I will expand the docs on the setup, I can imagine this point is not automatically clear.

**Comment by Frankniesten** [comment]
I'm experiencing the same problem.

The log shows the line:
`29 Aug 11:48:05 - [info] [nefit-easy-config:ee72c1cd.0702] Starting Nefit Easy Node for Node-RED.`

but a couple of lines further I get:
`29 Aug 11:48:06 - [error] [nefit-easy-config:ee72c1cd.0702] Nefit initialization : XMPP authentication failure`

**Comment by RaimondB** [comment]
The xmpp error means that you probably have not configured the key  / passwd correctly for your device. You need to fill out the same credentials you also use for the nefit app.

**Comment by RaimondB** [comment]
@Frankniesten @powergrim Is the issue still valid or solved by my added documentation?

**Comment by Frankniesten** [comment]
It's now working. I think the problem was that there were spaces in my password.

**Comment by RaimondB** [comment]
OK, go to hear. I hereby will close the issue
