### ISSUE TITLE
param null value errors

### ISSUE THREAD

**Issue by nachtbraker** [RaimondB/node-red-contrib-nefit-easy#172]
**Describe the bug**
I see these errors in the node-red log:

21 Aug 11:08:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command display-code (param null value undefined)
21 Aug 11:08:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command get-usermode (param null value undefined)
21 Aug 11:08:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command flow-temperature (param null value undefined)
21 Aug 11:09:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command status (param null value undefined)
21 Aug 11:09:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command display-code (param null value undefined)
21 Aug 11:09:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command get-usermode (param null value undefined)
21 Aug 11:09:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command flow-temperature (param null value undefined)
21 Aug 11:10:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command status (param null value undefined)
21 Aug 11:10:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command display-code (param null value undefined)
21 Aug 11:10:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command get-usermode (param null value undefined)
21 Aug 11:10:52 - [info] [nefit-easy-config:f6d215d8.125768] Nefit command flow-temperature (param null value undefined)

They seem harmless, as data comes in just fine. They just fill up the logs.

**To Reproduce**
Every minute several of the Nefit nodes are triggered to get the data.

**Expected behavior**
No errors

**Additional context**
FreeBSD 12.1
node10-10.21.0
node-red 1.0.6
node-red-contrib-nefit-easy2 2.0.0

**Comment by nachtbraker** [comment]
Is there some way of suppressing this? It's filling up 99% of my node-red log which makes it hard to read.

Thanks,
Ben

**Comment by RaimondB** [comment]
I'll look into it. Btw how often are you querying data? because it is not advised to do it more often than once a minute.

**Comment by nachtbraker** [comment]
Thank you.

Every minute I query 4 nodes with:
- Get status
- Get display boiler display statuscode
- Get user mode
- Get flow temperature

See screenshot below. So, that counts as 4 queries/minute?

<img width="586" alt="image" src="https://user-images.githubusercontent.com/29022937/91093631-faa7cc00-e659-11ea-8e5b-f1f2ecba0de2.png">

**Comment by RaimondB** [comment]
Indeed this is 4 queries. Altough that is not directly a problem. I have multiple nodes like this as well. When you do too much queries, the node will report an error mentioning MAX_RETRIES. So as long you don't get that, no problem :-)

I have released a 2.1.0 version that now offers a new config option with a checkbox to filter the command info messages. That way you still get the connect/disconnect info messages, but not the message per issued command. Also, the log messages are cleaned up to only show the value part when it is applicable for the selected command.

**Comment by nachtbraker** [comment]
Thank you, I appreciate the fast update. Installing it now!

I haven't seen the MAX_RETRIES error, but I will keep an eye on it.
