### ISSUE TITLE
The Bosch ct200

### ISSUE THREAD

**Issue by LucSieben** [RaimondB/node-red-contrib-nefit-easy#212]
Hi,

For a internship project I have to connect several things to Node-Red. (This is also my first time working with Node-Red).
On the company we have a Nefit Thermostat with the Bosch ct200 Smart Control, I tried out the pakkage but i think I did something wrong.
I write down the,
 - serial number,
 - accescode,
 - password.

But when I try to connect, I get a failure,
16 Mar 10:50:07 - [error] [nefit-easy-config:2c4118fa.f228e8] Nefit initialization : XMPP authentication failure.

Is there a way to connect this device to the Node?

Kind regrats,

Luc

**Comment by RaimondB** [comment]
Mostly this message means you have a wrong password. Another thing could be that your clock is out of sync.

Finally, I have only tested with Nefit easy. So I am not sure if this device uses the same firmware...

**Comment by LucSieben** [comment]
thanks for the reply, i did some research and found out that this device can't connect anyway my mistake sorry.
anyways thanks for the reply!
