### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by felix63** [RaimondB/node-red-contrib-nefit-easy#215]
I have added the node to the palette, configured using (working serial, key and pass) and imported your example. When I deploy I get 'disconnected'. I can find no further detailes of what goed wrong. But then I am a complete novice when it comes to Node-red. 
<img width="152" alt="image" src="https://user-images.githubusercontent.com/16501940/115157181-1a2bb300-a088-11eb-85a6-513909376380.png">

Do you have any pointers?

**Comment by RaimondB** [comment]
Do you have logs available? They should be listed on the right side in node-red. See also https://nodered.org/docs/user-guide/handling-errors

Another way is to look at the console log of node-red. How are you running node-red? Stand-alone or as part of a larger solution?

**Comment by felix63** [comment]
Hi Raimond,

I don't know any node-red log file, in syslog I can only find 
`[info] [nefit-easy-config:11021b28.b4f1ed] Starting Nefit Easy Node for Node-RED.`

And the debug window is empty...
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/16501940/115292145-e5862d00-a155-11eb-90db-b94f4674e88d.png">

I am using node-red as part of my domoticz setup. Nothing critical.

**Comment by RaimondB** [comment]
What happens when you click on the grey square left of the arrow in the inject node "TImer:timestamp" ? This should normally trigger a connection and retrieving information. It should at least produce some log messages.

**Comment by RaimondB** [comment]
You should be getting something like this:
![image](https://user-images.githubusercontent.com/12556944/115345538-3fffa780-a1af-11eb-813a-e0bd71da9ecd.png)

**Comment by felix63** [comment]
Nothing happens. Just the first time I get the red 'disconnected' but no error log. My assumption is that no connection to nefit server is possible. I am using the same proporties on a different machine to make a connection. There they work. But Node-red doesn't provide any feedback.

**Comment by RaimondB** [comment]
Ok, I'll try to see if I can reproduce with a firewall in place. Are there specific restrictions you have in place that I could try to replicate? Btw, I am using a library from https://github.com/robertklep/nefit-easy-commands .
So if it is a connectivity issue, it is probably located in there. The node red module only provides the node-red specfic wrapper and functionality.
