### ISSUE TITLE
XMPP authentication failure

### ISSUE THREAD

**Issue by snelweg** [RaimondB/node-red-contrib-nefit-easy#275]
why?

[node: 31304d70.bddaf2](http://192.168.1.121:1880/#)
msg : string[55]
"Nefit initialization error: XMPP authentication failure"

**Comment by RaimondB** [comment]
This normally means that a wrong username or password has been specified. Otherwise retry since it might have been a problem with the nefit servers.

**Comment by snelweg** [comment]
The problem seems to have solved itself after a apt disyt-upgrade.
Thank you for you response.
