### ISSUE TITLE
Node red won't start up after install node from Home Assistant Hassio

### ISSUE THREAD

**Issue by tsien-bier** [RaimondB/node-red-contrib-nefit-easy#9]
After installing node_red-contrib-nefit-easy from the node-red configuration nodes - install tab node-red wont't come up again. The web-interfaces is unavailable. When i check the log i see te following;

11 Dec 20:52:32 - [info] Installing module: node-red-contrib-nefit-easy2, version: 1.3.0
11 Dec 20:52:54 - [info] Installed module: node-red-contrib-nefit-easy2
11 Dec 20:52:56 - [info] Added node types:
11 Dec 20:52:56 - [info]  - node-red-contrib-nefit-easy2:nefit-easy
11 Dec 20:52:56 - [info]  - node-red-contrib-nefit-easy2:nefit-easy-config
11 Dec 20:52:56 - [red] Uncaught Exception:
11 Dec 20:52:56 - TypeError: tls.convertNPNProtocols is not a function
    at new TLSSocket (_tls_wrap.js:269:9)
    at Server.<anonymous> (_tls_wrap.js:852:18)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at TCP.onconnection (net.js:1570:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-11T19_52_56_108Z-debug.log
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
11 Dec 20:53:02 - [info] 

What is wrong here? I used the component before. Then there was no problem en could use the installed components en connect to my Nefit Easy.

**Comment by RaimondB** [comment]
To be able to find the cause, some questions.
Since which version of nefit-easy2 does this problem occur?
Does the problem go away when you uninstall nefit-easy2?
(to make sure it is not somthing else that changed in the same period)

**Comment by tsien-bier** [comment]
1. I don't know since which version of nefit-easy2 this problem occurs. I used it before with no problems about 2 months ago.
2. I can't uninstall from the nod-red web-interface because node-red isn't running so i have to restore from a back-up. Node red is running ok then.
3. I tried installing an other node and this is working well. The extra nodes  appear in the left node-red interface pane and are working.

**Comment by RaimondB** [comment]
1. To get the "last working version for you", when you restore the backup and go to the palette manager. When you go to the installed tab, and filter on "daylight" it should show the installed version.

2. You can also try uninstalling the npm way, by going to the directory where node-red's modules are  located (it is probably mentioned in the Hassio config) and then go into the .node-red directory.
(often it is located under the home directory of the user that is running the program, on linux based systems ~/.node-red

Then run 
`npm uninstall node-red-contrib-nefit-easy2
`
The problem should then go away and you could try a reinstall from the palette.
You can also install previously published versions by running (in the same directory)

`npm install node-red-contrib-easy2@1.2.0
`

**Comment by tsien-bier** [comment]
Already thank for your help. I'm a complete new on this platform and have to learn a lot. My programming and configuration skills are not up-to date.
1. I have nothing installed with comes up with the filter daylight. B.t.w. the working version of node-red-contrib-easy was in a previous installed version of hassio. (about 2 months ago) 
2. Can't run npm because hassio is a docker appliance of Home Assistant. Only specific HA commands will work on the command line. Installation is by a graphical system in Home Assistant addon store. This has a lot of advantages for people like me. Disadvantage is that tweaking and debugging is difficult.

**Comment by RaimondB** [comment]
Oops, sorry I was refering to the wrong node, please try to filter on nefit or easy. It will probably be version 1.2.0 (I expect)

**Comment by tsien-bier** [comment]
Tested the same with a ubuntu 18.4 server in Oracle Virtualbox. This is working well. No errors. I think the error has somthing to do with the way Node-Red is supplied in Hassio. As i explained before is node-red installed as add-on in Hassio. See: [https://community.home-assistant.io/t/community-hass-io-add-on-node-red/55023](url). I am going to post the error there and hope for a solution.

**Comment by RaimondB** [comment]
OK, in the mean time I will also try to get a Hassio setup so that I can maybe detect what's going on to see if it has a relation with a library in the nefit module.

**Comment by tsien-bier** [comment]
Posted the error [here](https://github.com/hassio-addons/addon-node-red/issues/94) also.

**Comment by RaimondB** [comment]
I thought it might be realted to running nwer versions of NodeJS. I have tested it also with Node 10 and confirmed that this works as expected. So the Node JS version does not seem to be the issue

**Comment by tsien-bier** [comment]
Frenk (Creator of Hassio add-on node-red) answerd: 

> Seems like it is missing some libraries that the node needs?
> Not sure. I cannot support all nodes out there, that would be impossible.
> I'm sorry to say, but in this case, you are on your own.
> Maybe somebody in the community is able to help? 
 
The problem isn't solved now. Node Red refuses to run when loading the Nefit-Node.

**Comment by RaimondB** [comment]
There is a seemingly related issue mentioned on the base library for nefit that I am using:
https://github.com/robertklep/homebridge-nefit-easy/issues/12

Maybe they can clarify how they managed to solve the problem.

**Comment by RaimondB** [comment]
The function mentioned seems to be removed in NodeJS 10 and deprecated since NodeJS 9.
https://github.com/nodejs/node/issues/14602

@tsien-bier  What version of NodeJS is running in your setup?

**Comment by tsien-bier** [comment]
The log says:
```
28 Dec 17:17:45 - [info] Node-RED version: v0.19.5
28 Dec 17:17:45 - [info] Node.js  version: v8.14.0
28 Dec 17:17:45 - [info] Linux 4.14.78-v7 arm LE
28 Dec 17:17:46 - [info] Loading palette nodes
28 Dec 17:17:51 - [info] Settings file  : /etc/node-red/config.js
28 Dec 17:17:51 - [info] Context store  : 'default' [module=memory]
28 Dec 17:17:51 - [info] User directory : /config/node-red/
28 Dec 17:17:51 - [warn] Projects disabled : editorTheme.projects.enabled=false
28 Dec 17:17:51 - [info] Flows file     : /config/node-red/flows.json
28 Dec 17:17:51 - [info] Server now running at https://127.0.0.1:1880/
28 Dec 17:17:51 - [info] Starting flows
28 Dec 17:17:51 - [info] Started flows
28 Dec 17:17:51 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
```
So it has to be:  v8.14.0

**Comment by RaimondB** [comment]
I tried Node 8.14 and this works, so the node version is not the issue. As stated in the other issue at the base nefit libraries, it must be related to one of the other plugins being outdated. You could try a clean setup of hassio/node-red with just the nefit-easy node. This should work. 
Then start adding the other nodes/plugins one by one. As soon as things break down, you have found the culprit ;-)

**Comment by tsien-bier** [comment]
I'm going to try the your suggestions. I didn't install any nodes via the palette, it is a clean install of hassio node-red install. So an other node can not be the issue.

**Comment by tsien-bier** [comment]
Tested it again with a clean node-red addon installation. Again the nefit node causes my node-red service to crash. After clicking install I get the massage "Nodes add to Pallet (Two Nefit nodes). Some seconds after that massage the message "Lost connection to server. Reconnect ...... The log looks the seam as the first message in this Issue. 
I don't have any ideas to solve this problem. Maybe another Home Assistant installation should be better. I'm thinking about Hasbian. The disadvantage is that there are no add-ons but maybe also less errors.

**Comment by tsien-bier** [comment]
Solved the issue now. I found a work-arround. In stead of adding the node fia the UI of node-red i placed the addon in the config file of hassio.:

```
{
  "log_level": "info",
  "credential_secret": "ktktest",
  "http_node": {
    "username": "ktk",
    "password": "ktksecr"
  },
  "http_static": {
    "username": "ktk",
    "password": "ktksecr"
  },
  "port": 1880,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": false,
  "system_packages": [],
  "npm_packages": [
    "node-red-contrib-nefit-easy2"
  ],
  "init_commands": []
}
```
Now the nefit node is in the Node-red UI and i can configure the node.

But the node is not working as espected. I get no info from the Bosch Server. 

I come back here with more information.

Now the folowing issue appaers: I get a warning at startup:
```
[cont-init.d] 81-npm-packages.sh: executing... 
npm WARN node-red-contrib-nefit-easy2@1.4.0 requires a peer of node-red@~0.18.4 but none is installed. You must install peer dependencies yourself.
+ node-red-contrib-nefit-easy2@1.4.0
added 30 packages from 33 contributors, updated 4 packages and audited 2325 packages in 38.163s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```
After configuring the Nefit node-component i get no info: the log says:

**Comment by RaimondB** [comment]
I have just published a new version 1.4.1 in which the peerDependency is removed. It is only needed to develop on the node, not for running it so it is redundant.
However, this is just a warning and should not influence the operation.

Also, it seems that by default hassio adds a lot of packages already.
```
added 30 packages from 33 contributors, updated 4 packages and audited 2325 packages in 38.163s
found 2 vulnerabilities (1 low, 1 moderate)
```
Btw, when I run npm audit on the nefit2 module itself, I get this result:
```
                       === npm audit security report ===

found 0 vulnerabilities
 in 1930 scanned packages
```
So the vulnerabilities must be coming from one of the already installed packages by hassio nodered addon.

**Comment by tsien-bier** [comment]
Changed the password. The problem was that i used the API password that i used with IFTTT. This password appear not to be the same as the mobile app. Everything is now working.

I'm very happy i can now continue with my little hobby project at home. 

Thanks for your help and i wish you a good Sunday.

**Comment by RaimondB** [comment]
Great, good to hear :-)
